import { BusinessMetadataDto } from "./businessMetadataSchema";

export const businessMetadataInitialValues: BusinessMetadataDto = {
  companyName: "",
  tradingName: "",
  websiteUrl: "",
  natureOfBusiness: "",
  companyRegistrationNumber: "",
  companyType: "",
  // isVatRegistered: undefined,
  isVatRegistered: true,
  vatNumber: "",

  isPubliclyTrading: undefined,
  // isPubliclyTrading: true,
  stockMarketLocation: "IM",
  stockMarket: "",

  // isRegulated: undefined,
  isRegulated: true,
  regulatorName: "",
  legalEntity: "",
  email: "",
  otherTradingNames: "",
  countryOfRegistration: "",
  dateOfRegistration: "",
  telephoneNumber: "",
  dateOfIncorporation: "",
  statutoryProvision: "",
  registeredOffice1: "",
  registeredOffice1_address2: "",
  registeredOffice1_city: "",
  registeredOffice1_postcode: "",
  registeredOffice1_state: "",
  registeredOffice2: "",
  registeredOffice3: "",
  principalPlace: "",
  mailingAddress: "",
  previousOffice1: "",
  previousOffice2: "",
  previousOffice3: "",
  expectedActivity: "",
  expectedVolume: "",
  otherContactInfo: "",
};
