import { User } from "../../auth/AuthApi";
import { IndividualMetadataDto } from "./individualMetadataSchema";

export const createIndividualMetadataInitialValues = (user: User | null): IndividualMetadataDto => ({
  title: 'Mr.',
  firstname: user?.firstname || '',
  lastname: user?.lastname || '',
  formerName: '',
  otherName: '',
  dateOfBirth: undefined,
  placeOfBirth: '',
  addressLine1: '',
  addressLine2: '',
  city: '',
  state: '',
  postcode: '',
  country: '',
  skipPreviousAddress: true,
  previousAddressLine1: '',
  previousAddressLine2: '',
  previousCity: '',
  previousPostcode: '',
  previousState: '',
  previousCountry: '',
  nationality: '',
  gender: '',
  identificationNumber: '',
  identificationType: '',
  occupation: '',
  employerName: '',
  employerAddress1: '',
  employerAddress2: '',
  employerAddress3: '',
  publicPosition: '',
  highProfilePosition: '',
});
