import { AccountDto, ContactDto, SettleAccountDto } from "./account-dto";

export const initialAccountValues: AccountDto = {
  id: "",
  account_name: "",
  brand: "",
  your_reference: "",
  status: "",
  street: "",
  city: "",
  state_or_province: "",
  country: "",
  postal_code: "",
  spread_table: "",
  legal_entity_type: "",
  identification_type: "",
  identification_value: "",
  short_reference: "",
  api_trading: "",
  online_trading: "",
  phone_trading: "",
  process_third_party_funds: "",
  settlement_type: "",
  agent_or_reliance: "",
  terms_and_conditions_accepted: "",
  bank_account_verified: "",
  cloudCurrencyId: "",
  openPaydId: "",
  isApproved: false,
}

export const initialContactValues: ContactDto = {
  login_id: "",
  id: "",
  first_name: "",
  last_name: "",
  account_id: "",
  account_name: "",
  status: "",
  locale: "",
  timezone: "",
  email_address: "",
  mobile_phone_number: "",
  phone_number: "",
  your_reference: "",
  date_of_birth: "",
  account: initialAccountValues,
  complyLaunchId: '',
}
export const initialSettleAccountValues: SettleAccountDto = {
  login_id: "",
  id: "",
  first_name: "",
  last_name: "",
  account_id: "",
  account_name: "",
  status: "",
  locale: "",
  timezone: "",
  email_address: "",
  mobile_phone_number: "",
  phone_number: "",
  your_reference: "",
  date_of_birth: "",
  bank_account_holder_name: "",
  beneficiary_address: "",
  beneficiary_country: "",
  bank_name: "",
  bank_address: "",
  bank_country: "",
  currency: "",
  bic_swift: "",
  iban: "",
  account_number: "",
  routing_code_type_1: "",
  routing_code_value_1: "",
  routing_code_type_2: "",
  routing_code_value_2: "",
}
