apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lux-bank

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - postgres-setup.yaml
  - api-deployment.yaml
  - dash-deployment.yaml
  - admin-deployment.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: lux-bank
    includeSelectors: false
