apiVersion: v1
kind: Secret
metadata:
  name: bank-secrets
  namespace: lux-bank
type: Opaque
stringData:
  db-password: "CHANGE_ME"
  jwt-secret: "CHANGE_ME"
  admin-email: "z@lux.network"
  recaptcha-site-key: "CHANGE_ME"
  recaptcha-secret-key: "CHANGE_ME"
  sendgrid-key: "CHANGE_ME"
  encrypt-key: "CHANGE_ME"
  sentry-dsn: "CHANGE_ME"
