export enum IdentificationType {
  None = '',
  DriversLicense = 'drivers_license',
  SocialSecurityNumber = 'social_security_number',
  GreenCard = 'green_card',
  Passport = 'passport',
  Visa = 'visa',
  MatriculaConsular = 'matricula_consular',
  RegistroFederalDeContribuyentes = 'registro_federal_de_contribuyentes',
  ClaveUnicaDeRegistroDePoblacion = 'clave_unica_de_registro_de_poblacion',
  CredentialDeElector = 'credential_de_elector',
  SocialInsuranceNumber = 'social_insurance_number',
  CitizenshipPapers = 'citizenship_papers',
  DriversLicenseCanadian = 'drivers_license_canadian',
  ExistingCreditCardDetails = 'existing_credit_card_details',
  EmployerIdentificationNumber = 'employer_identification_number',
  NationalId = 'national_id',
  IncorporationNumber = 'incorporation_number',
  Others = 'others',
}
