export enum LinkedClientCompanyType {
    LIMITED_LIABILITY = 'LIMITED_LIABILITY',
    SOLE_TRADER = 'SOLE_TRADER',
    PARTNERSHIP = 'PARTNERSHIP',
    PUBLIC_LIMITED_COMPANY = 'PUBLIC_LIMITED_COMPANY',
    JOINT_STOCK_COMPANY = 'JOINT_STOCK_COMPANY',
    CHARITY = 'CHARITY'
}