export enum IdentificationType {
  None = 'none',
  DriversLicense = 'drivers_license',
  SocialSecurityNumber = 'social_security_number',
  GreenCard = 'green_card',
  Passport = 'passport',
  Visa = 'visa',
  MatriculaConsular = 'matricula_consular',
  RegistroFederalDeContribuyentes = 'registro_federal_de_contribuyentes',
  CredentialDeElector = 'credential_de_elector',
  SocialInsuranceNumber = 'social_insurance_number',
  CitizenshipPapers = 'citizenship_papers',
  DriversLicenseCanadian = 'drivers_license_canadian',
  ExistingCreditCardDetails = 'existing_credit_card_details',
  EmployerIdentificationNumber = 'employer_identification_number',
  NationalId = 'national_id',
  Others = 'others',
  IncorporationNumber = 'incorporation_number',
}
