export const customers: Map<string, string> = new Map(Object.entries({
  'buy': 'Buy',
  'sell': 'Sell'
}));
const currenciesArray = {
  'GBP': 'GBP',
  'USD': 'USD',
  'EUR': 'EUR',
  'AED': 'AED',
	'AUD': 'AUD',
  'BGN': 'BGN',
  'BHD': 'BHD',
  'CAD': 'CAD',
  'CHF': 'CHF',
  'CLP': 'CLP',
  'CNY': 'CNY',
  'CZK': 'CZK',
  'DKK': 'DKK',
  'HKD': 'HKD',
  'HRK': 'HRK',
  'HUF': 'HUF',
  'IDR': 'IDR',
  'ILS': 'ILS',
  'INR': 'INR',
  'JMD': 'JMD',
  'JOD': 'JOD',
  'JPY': 'JPY',
  'KES': 'KES',
  'KWD': 'KWD',
  'MXN': 'MXN',
  'MYR': 'MYR',
  'NAD': 'NAD',
  'NOK': 'NOK',
  'NZD': 'NZD',
  'OMR': 'OMR',
  'PHP': 'PHP',
  'PLN': 'PLN',
  'QAR': 'QAR',
  'RON': 'RON',
  'RUB': 'RUB',
  'SAR': 'SAR',
  'SEK': 'SEK',
  'SGD': 'SGD',
  'THB': 'THB',
  'TND': 'TND',
  'TRY': 'TRY',
  'UGX': 'UGX',
  'ZAR': 'ZAR',
};
export const currencies: Map<string, string> = new Map(Object.entries(currenciesArray));
export const currenciesToSelect: Map<string, string> = new Map(Object.entries({
  '':'Select a currency',
  ...currenciesArray
}));
