export const Constants = {
  HOMEPAGE_URL: 'https://www.cdaxforex.com/',
  PRIVACY_POLICY_URL: '/privacy_policy',
  TERMS_OF_SERVICE_URL: 'https://app.stg.cdaxforex.com/terms_and_conditions',
  REGISTRATION_HELP:
    'https://www.cdaxforex.com/help/how-do-i-register-for-a-cdax-forex-account',
  JWT_COOKIE_NAME: 'cdax-jwt-session',
  CREATE_A_PAYMENT_URL: '#',
  HELP_CENTRE_URL: 'https://www.cdaxforex.com/help-centre/',
};

export const size = {
  xs: '320px',
  sm: '768px',
  lg: '1200px',
};

export const DeviceSize = {
  xs: `(max-width: ${size.xs})`,
  sm: `(max-width: ${size.sm})`,
  lg: `(max-width: ${size.lg})`,
};

export const MonthsList: Map<string, string> = new Map(
  Object.entries({
    Jan: 'Jan',
    Feb: 'Feb',
    Mar: 'Mar',
    Apr: 'Apr',
    May: 'May',
    Jun: 'Jun',
    Jul: 'Jul',
    Aug: 'Aug',
    Sep: 'Sep',
    Oct: 'Oct',
    Nov: 'Nov',
    Dec: 'Dec',
  })
);

export const CountriesList: Map<string, string> = new Map(
  Object.entries({
    IM: 'Isle of Man ',
    GB: 'United Kingdom ',
    US: 'United States of America ',
    AF: 'Afghanistan ',
    AL: 'Albania ',
    DZ: 'Algeria ',
    AS: 'American Samoa ',
    AD: 'Andorra ',
    AO: 'Angola ',
    AI: 'Anguilla ',
    AQ: 'Antarctica ',
    AG: 'Antigua and Barbuda ',
    AR: 'Argentina ',
    AM: 'Armenia ',
    AW: 'Aruba ',
    AU: 'Australia ',
    AT: 'Austria ',
    AZ: 'Azerbaijan ',
    BS: 'Bahamas (the) ',
    BH: 'Bahrain ',
    BD: 'Bangladesh ',
    BB: 'Barbados ',
    BY: 'Belarus ',
    BE: 'Belgium ',
    BZ: 'Belize ',
    BJ: 'Benin ',
    BM: 'Bermuda ',
    BT: 'Bhutan ',
    BO: 'Bolivia (Plurinational State of) ',
    BQ: 'Bonaire, Sint Eustatius and Saba ',
    BA: 'Bosnia and Herzegovina ',
    BW: 'Botswana ',
    BV: 'Bouvet Island ',
    BR: 'Brazil ',
    IO: 'British Indian Ocean Territory (the) ',
    BN: 'Brunei Darussalam ',
    BG: 'Bulgaria ',
    BF: 'Burkina Faso ',
    BI: 'Burundi ',
    CV: 'Cabo Verde ',
    KH: 'Cambodia ',
    CM: 'Cameroon ',
    CA: 'Canada ',
    KY: 'Cayman Islands (the) ',
    CF: 'Central African Republic (the) ',
    TD: 'Chad ',
    CL: 'Chile ',
    CN: 'China ',
    CX: 'Christmas Island ',
    CC: 'Cocos (Keeling) Islands (the) ',
    CO: 'Colombia ',
    KM: 'Comoros (the) ',
    CD: 'Congo (the Democratic Republic of the) ',
    CG: 'Congo (the) ',
    CK: 'Cook Islands (the) ',
    CR: 'Costa Rica ',
    HR: 'Croatia ',
    CU: 'Cuba ',
    CW: 'Curaçao ',
    CY: 'Cyprus ',
    CZ: 'Czechia ',
    CI: 'Côte dIvoire ',
    DK: 'Denmark ',
    DJ: 'Djibouti ',
    DM: 'Dominica ',
    DO: 'Dominican Republic (the) ',
    EC: 'Ecuador ',
    EG: 'Egypt ',
    SV: 'El Salvador ',
    GQ: 'Equatorial Guinea ',
    ER: 'Eritrea ',
    EE: 'Estonia ',
    SZ: 'Eswatini ',
    ET: 'Ethiopia ',
    FK: 'Falkland Islands (the) [Malvinas] ',
    FO: 'Faroe Islands (the) ',
    FJ: 'Fiji ',
    FI: 'Finland ',
    FR: 'France ',
    GF: 'French Guiana ',
    PF: 'French Polynesia ',
    TF: 'French Southern Territories (the) ',
    GA: 'Gabon ',
    GM: 'Gambia (the) ',
    GE: 'Georgia ',
    DE: 'Germany ',
    GH: 'Ghana ',
    GI: 'Gibraltar ',
    GR: 'Greece ',
    GL: 'Greenland ',
    GD: 'Grenada ',
    GP: 'Guadeloupe ',
    GU: 'Guam ',
    GT: 'Guatemala ',
    GG: 'Guernsey ',
    GN: 'Guinea ',
    GW: 'Guinea-Bissau ',
    GY: 'Guyana ',
    HT: 'Haiti ',
    HM: 'Heard Island and McDonald Islands ',
    VA: 'Holy See (the) ',
    HN: 'Honduras ',
    HK: 'Hong Kong ',
    HU: 'Hungary ',
    IS: 'Iceland ',
    IN: 'India ',
    ID: 'Indonesia ',
    IR: 'Iran (Islamic Republic of) ',
    IQ: 'Iraq ',
    IE: 'Ireland ',
    IL: 'Israel ',
    IT: 'Italy ',
    JM: 'Jamaica ',
    JP: 'Japan ',
    JE: 'Jersey ',
    JO: 'Jordan ',
    KZ: 'Kazakhstan ',
    KE: 'Kenya ',
    KI: 'Kiribati ',
    KP: "Korea (the Democratic People's Republic of) ",
    KR: 'Korea (the Republic of) ',
    KW: 'Kuwait ',
    KG: 'Kyrgyzstan ',
    LA: "Lao People's Democratic Republic(the) ",
    LV: 'Latvia ',
    LB: 'Lebanon ',
    LS: 'Lesotho ',
    LR: 'Liberia ',
    LY: 'Libya ',
    LI: 'Liechtenstein ',
    LT: 'Lithuania ',
    LU: 'Luxembourg ',
    MO: 'Macao ',
    MG: 'Madagascar ',
    MW: 'Malawi ',
    MY: 'Malaysia ',
    MV: 'Maldives ',
    ML: 'Mali ',
    MT: 'Malta ',
    MH: 'Marshall Islands (the) ',
    MQ: 'Martinique ',
    MR: 'Mauritania ',
    MU: 'Mauritius ',
    YT: 'Mayotte ',
    MX: 'Mexico ',
    FM: 'Micronesia (Federated States of) ',
    MD: 'Moldova (the Republic of) ',
    MC: 'Monaco ',
    MN: 'Mongolia ',
    ME: 'Montenegro ',
    MS: 'Montserrat ',
    MA: 'Morocco ',
    MZ: 'Mozambique ',
    MM: 'Myanmar ',
    NA: 'Namibia ',
    NR: 'Nauru ',
    NP: 'Nepal ',
    NL: 'Netherlands (the) ',
    NC: 'New Caledonia ',
    NZ: 'New Zealand ',
    NI: 'Nicaragua ',
    NE: 'Niger (the) ',
    NG: 'Nigeria ',
    NU: 'Niue ',
    NF: 'Norfolk Island ',
    MP: 'Northern Mariana Islands (the) ',
    NO: 'Norway ',
    OM: 'Oman ',
    PK: 'Pakistan ',
    PW: 'Palau ',
    PS: 'Palestine, State of ',
    PA: 'Panama ',
    PG: 'Papua New Guinea ',
    PY: 'Paraguay ',
    PE: 'Peru ',
    PH: 'Philippines (the) ',
    PN: 'Pitcairn ',
    PL: 'Poland ',
    PT: 'Portugal ',
    PR: 'Puerto Rico ',
    QA: 'Qatar ',
    MK: 'Republic of North Macedonia ',
    RO: 'Romania ',
    RU: 'Russian Federation (the) ',
    RW: 'Rwanda ',
    RE: 'Réunion ',
    BL: 'Saint Barthélemy ',
    SH: 'Saint Helena, Ascension and Tristan da Cunha ',
    KN: 'Saint Kitts and Nevis ',
    LC: 'Saint Lucia ',
    MF: 'Saint Martin (French part) ',
    PM: 'Saint Pierre and Miquelon ',
    VC: 'Saint Vincent and the Grenadines ',
    WS: 'Samoa ',
    SM: 'San Marino ',
    ST: 'Sao Tome and Principe ',
    SA: 'Saudi Arabia ',
    SN: 'Senegal ',
    RS: 'Serbia ',
    SC: 'Seychelles ',
    SL: 'Sierra Leone ',
    SG: 'Singapore ',
    SX: 'Sint Maarten (Dutch part) ',
    SK: 'Slovakia ',
    SI: 'Slovenia ',
    SB: 'Solomon Islands ',
    SO: 'Somalia ',
    ZA: 'South Africa ',
    GS: 'South Georgia and the South Sandwich Islands ',
    SS: 'South Sudan ',
    ES: 'Spain ',
    LK: 'Sri Lanka ',
    SD: 'Sudan (the) ',
    SR: 'Suriname ',
    SJ: 'Svalbard and Jan Mayen ',
    SE: 'Sweden ',
    CH: 'Switzerland ',
    SY: 'Syrian Arab Republic ',
    TW: 'Taiwan ',
    TJ: 'Tajikistan ',
    TZ: 'Tanzania, United Republic of ',
    TH: 'Thailand ',
    TL: 'Timor-Leste ',
    TG: 'Togo ',
    TK: 'Tokelau ',
    TO: 'Tonga ',
    TT: 'Trinidad and Tobago ',
    TN: 'Tunisia ',
    TR: 'Turkey ',
    TM: 'Turkmenistan ',
    TC: 'Turks and Caicos Islands ',
    TV: 'Tuvalu ',
    UG: 'Uganda ',
    UA: 'Ukraine ',
    AE: 'United Arab Emirates ',
    UM: 'United States Minor Outlying Islands ',
    UY: 'Uruguay ',
    UZ: 'Uzbekistan ',
    VU: 'Vanuatu ',
    VE: 'Venezuela ',
    VN: 'Vietnam ',
    VG: 'Virgin Islands (British) ',
    VI: 'Virgin Islands (U.S.) ',
    WF: 'Wallis and Futuna ',
    EH: 'Western Sahara ',
    YE: 'Yemen ',
    ZM: 'Zambia ',
    ZW: 'Zimbabwe ',
  })
);

export const YesOrNo: Map<string, string> = new Map(
  Object.entries({
    yes: 'Yes',
    no: 'No',
  })
);

export const CompanyType: Map<string, string> = new Map(
  Object.entries({
    LIMITED_LIABILITY: 'Limited Liability',
    PARTNERSHIP: 'Partnership',
    CHARITY: 'Charity',
    JOINT_STOCK_COMPANY: 'Joint Stock Company',
    PUBLIC_LIMITED_COMPANY: 'Public Limited Company',
  })
);
